language: android
cache:
  directories:
    - haoshiyou/node_modules
notifications:
  email: false
android:
  components:
    - build-tools-23.0.1
    - android-23
before_install:
  - npm list -g npm@3.9.6 --depth=0 || npm i -g npm@3.9.6
  - npm list -g ionic@2.0.0-beta.31 --depth=0 || npm install -g ionic@2.0.0-beta.31
  - npm list -g cordova@6.2.0 --depth=0 || npm install -g cordova@6.2.0
install: 
  - cd haoshiyou 
  - npm install
script: 
  - ionic build android # build