# To test if your modification to this file works, go to http://lint.travis-ci.org/.
language: node_js
node_js:
  - "4.4.4"
env:
  CXX=g++-4.8
  global:
    ANDROID_HOME=$PWD/android-sdk-linux
    PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2
os:
  - osx
cache:
  directories:
    - haoshiyou/node_modules
notifications:
  slack: haoshiyou:eSZq9zT9wMllEJYHMITggGky
before_install:
  - cd haoshiyou 
  # download config.json from haoshiyou-security repository with a token
  - ./travis/download-config.sh
  - ./travis/install-android-sdk.sh
install:
  - ./travis/install-ionic-sdk.sh
  - npm install
  - ionic platform remove android
  - ionic platform add android
script:
  - ionic build android
