# To test if your modification to this file works, go to http://lint.travis-ci.org/.
language: node_js
env:
  CXX=g++-4.8
node_js:
  - '4.4'
matrix:
  fast_finish: true
os:
  - linux
  - osx
cache:
  directories:
    - haoshiyou/node_modules
notifications:
  slack: haoshiyou:eSZq9zT9wMllEJYHMITggGky
before_install:
  - cd haoshiyou 
  # download config.json from haoshiyou-security repository with a token
  - ./travis/download-config.sh
  - ./travis/install-platform-sdk.sh
install:
  - ./travis/install-ionic-sdk.sh
  - npm install
script:
  - ./travis/build-platform.sh
  - gulp  --gulpfile test/gulpfile.ts --cwd ./ unit-test 
